# fly.toml app configuration file generated for estate-static-ip-egress-proxy on 2024-12-20T13:59:25+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'estate-static-ip-egress-proxy'
primary_region = 'ams'

[env]
RUST_LOG="debug"

[build]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
internal_port = 80
protocol = "tcp"
http_checks = []

[[services.ports]]
handlers = ["http"] 
port = 80

